"""
Cross-language parity harness — verifies the Python port produces
byte-identical output to the TypeScript reference for all core functions.

Fixtures are generated by parity_reference.mjs (standalone, no workspace deps)
and committed alongside this test. Regenerate with:
    node parity_reference.mjs > parity_fixtures.json
"""

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from services.focus import (
    FocusRow,
    SavingOpportunity,
    apply_filters,
    build_dataset,
    build_savings_opportunities,
    cost_of,
    get_savings,
    hash_seed,
    load_dataset,
    mulberry32,
    naive_sum,
    reset_dataset_cache,
    sum_cost,
    ym_key,
)

FIXTURES_PATH = Path(__file__).parent / "parity_fixtures.json"


def _iso_js(dt: datetime) -> str:
    return dt.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%S.") + "000Z"


@pytest.fixture(scope="module")
def fixtures():
    with open(FIXTURES_PATH) as f:
        return json.load(f)


@pytest.fixture(autouse=True)
def _reset_cache():
    """Ensure each test group starts with a fresh dataset cache."""
    reset_dataset_cache()
    yield
    reset_dataset_cache()


UTC = timezone.utc


class TestMulberry32Parity:
    def test_prng_determinism(self, fixtures):
        for seed, expected_outputs in zip(
            fixtures["prng"]["seeds"],
            fixtures["prng"]["outputs"],
        ):
            rand = mulberry32(seed)
            for expected in expected_outputs:
                actual = round(rand(), 4)
                assert actual == expected, (
                    f"mulberry32({seed}): expected {expected}, got {actual}"
                )


class TestHashSeedParity:
    def test_hash_seed_determinism(self, fixtures):
        inputs = [
            ("2026-01-01T00:00:00.000Z", "AWS", "Amazon EC2", "platform", "checkout"),
            ("2026-01-01T00:00:00.000Z", "Azure", "Azure OpenAI", "ml", "recommendations"),
            ("2025-06-01T00:00:00.000Z", "GCP", "BigQuery", "data", "analytics"),
        ]
        for args, expected in zip(inputs, fixtures["prng"]["seeds"]):
            actual = hash_seed(*args)
            assert actual == expected, (
                f"hash_seed({args}): expected {expected}, got {actual}"
            )


class TestYmKeyParity:
    def test_ym_key_format(self, fixtures):
        test_dates = [
            "2026-01-15T00:00:00.000Z",
            "2025-12-31T23:59:59.000Z",
            "2025-03-01T00:00:00.000Z",
        ]
        for date_str, expected in zip(test_dates, fixtures["ymKey"]):
            dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
            actual = ym_key(dt)
            assert actual == expected, (
                f"ym_key({date_str}): expected {expected}, got {actual}"
            )


class TestDatasetParity:
    def test_dataset_shape(self, fixtures):
        ds = build_dataset()
        assert _iso_js(ds["startDate"]) == fixtures["dataset"]["startDate"]
        assert _iso_js(ds["endDate"]) == fixtures["dataset"]["endDate"]
        assert len(ds["monthlyRows"]) == fixtures["dataset"]["totalRows"]

    def test_dataset_categories(self, fixtures):
        ds = build_dataset()
        categories = sorted({r.ServiceCategory for r in ds["monthlyRows"]})
        assert categories == fixtures["dataset"]["categories"]

    def test_dataset_resource_id_pattern(self, fixtures):
        ds = build_dataset()
        samples = [r.x_ResourceId for r in ds["monthlyRows"][:5]]
        assert samples == fixtures["resourceIdSamples"]


class TestAggregationParity:
    def test_all_providers_effective(self, fixtures):
        ds = build_dataset()
        actual = round(sum_cost(ds["monthlyRows"], "EffectiveCost"), 2)
        expected = fixtures["aggregation"]["allProviders"]["effectiveCost"]
        assert actual == expected, f"allProviders.effectiveCost: {actual} != {expected}"

    def test_all_providers_billed(self, fixtures):
        ds = build_dataset()
        actual = round(sum_cost(ds["monthlyRows"], "BilledCost"), 2)
        expected = fixtures["aggregation"]["allProviders"]["billedCost"]
        assert actual == expected, f"allProviders.billedCost: {actual} != {expected}"

    def test_aws_only(self, fixtures):
        ds = build_dataset()
        aws_rows = apply_filters(ds["monthlyRows"], {"providers": ["AWS"]})
        assert round(sum_cost(aws_rows, "EffectiveCost"), 2) == fixtures["aggregation"]["awsOnly"]["effectiveCost"]
        assert round(sum_cost(aws_rows, "BilledCost"), 2) == fixtures["aggregation"]["awsOnly"]["billedCost"]
        assert len(aws_rows) == fixtures["aggregation"]["awsOnly"]["rowCount"]

    def test_ml_team_only(self, fixtures):
        ds = build_dataset()
        ml_rows = apply_filters(ds["monthlyRows"], {"teams": ["ml"]})
        assert round(sum_cost(ml_rows, "EffectiveCost"), 2) == fixtures["aggregation"]["mlTeamOnly"]["effectiveCost"]
        assert len(ml_rows) == fixtures["aggregation"]["mlTeamOnly"]["rowCount"]

    def test_jan_2026_only(self, fixtures):
        ds = build_dataset()
        jan_start = datetime(2026, 1, 1, tzinfo=UTC)
        jan_end = datetime(2026, 2, 1, tzinfo=UTC)
        jan_rows = apply_filters(ds["monthlyRows"], {"startDate": jan_start, "endDate": jan_end})
        assert round(sum_cost(jan_rows, "EffectiveCost"), 2) == fixtures["aggregation"]["jan2026Only"]["effectiveCost"]
        assert len(jan_rows) == fixtures["aggregation"]["jan2026Only"]["rowCount"]

    def test_aws_and_ml_combined(self, fixtures):
        ds = build_dataset()
        rows = apply_filters(ds["monthlyRows"], {"providers": ["AWS"], "teams": ["ml"]})
        assert round(sum_cost(rows, "EffectiveCost"), 2) == fixtures["aggregation"]["awsAndMl"]["effectiveCost"]
        assert len(rows) == fixtures["aggregation"]["awsAndMl"]["rowCount"]


class TestBreakdownParity:
    def test_by_provider_totals(self, fixtures):
        ds = build_dataset()
        by_provider = {}
        for r in ds["monthlyRows"]:
            by_provider[r.ProviderName] = by_provider.get(r.ProviderName, 0) + cost_of(r, "EffectiveCost")
        for provider, expected in fixtures["breakdown"]["byProvider"].items():
            actual = round(by_provider.get(provider, 0), 2)
            assert actual == expected, f"byProvider[{provider}]: {actual} != {expected}"


class TestTimeseriesParity:
    def test_monthly_totals(self, fixtures):
        ds = build_dataset()
        by_month = {}
        for r in ds["monthlyRows"]:
            key = ym_key(r.ChargePeriodStart)
            by_month[key] = by_month.get(key, 0) + cost_of(r, "EffectiveCost")
        for month, expected in fixtures["timeseries"]["byMonth"].items():
            actual = round(by_month.get(month, 0), 2)
            assert actual == expected, f"byMonth[{month}]: {actual} != {expected}"


class TestSavingsParity:
    def test_savings_count_and_total(self, fixtures):
        savings = build_savings_opportunities()
        assert len(savings) == fixtures["savings"]["totalCount"]
        total = round(sum(s.monthlySavings for s in savings), 2)
        assert total == fixtures["savings"]["totalMonthlySavings"]

    def test_aws_savings(self, fixtures):
        aws = get_savings({"providers": ["AWS"]})
        assert len(aws) == fixtures["savings"]["awsCount"]
        total = round(sum(s.monthlySavings for s in aws), 2)
        assert total == fixtures["savings"]["awsTotalMonthlySavings"]

    def test_ml_savings(self, fixtures):
        ml = get_savings({"teams": ["ml"]})
        assert len(ml) == fixtures["savings"]["mlCount"]
        total = round(sum(s.monthlySavings for s in ml), 2)
        assert total == fixtures["savings"]["mlTotalMonthlySavings"]

    def test_resource_id_presence(self, fixtures):
        savings = build_savings_opportunities()
        by_id = {s.id: s for s in savings}
        for entry in fixtures["savings"]["resourceIdPresence"]:
            s = by_id[entry["id"]]
            has_id = s.resourceId is not None
            assert has_id == entry["hasResourceId"], (
                f"{entry['id']}: resourceId presence {has_id} != {entry['hasResourceId']}"
            )

    def test_savings_serialization_parity(self, fixtures):
        savings = build_savings_opportunities()
        for s in savings:
            if s.resourceId is None:
                # TS serializes undefined as missing key — Python should omit it
                data = {
                    "id": s.id,
                    "title": s.title,
                    "category": s.category,
                    "provider": s.provider,
                    "service": s.service,
                    "team": s.team,
                    "product": s.product,
                    "monthlySavings": round(s.monthlySavings, 2),
                    "currency": s.currency,
                    "recommendedAction": s.recommendedAction,
                    "effort": s.effort,
                    "details": s.details,
                }
                assert "resourceId" not in data


class TestLoadDatasetParity:
    def test_mock_source(self):
        ds = load_dataset(tenant_id=1, data_source="mock")
        assert ds["source"] == "mock"
        assert len(ds["monthlyRows"]) > 0

    def test_live_source_empty(self):
        ds = load_dataset(tenant_id=1, data_source="live")
        assert ds["source"] == "live"
        assert len(ds["monthlyRows"]) == 0
